/* 
 * tcllibxml2StubInit.c --
 */

#include <tclxml-libxml2/tclxml-libxml2.h>

/*
 * Remove macros that will interfere with the definitions below.
 */


/*
 * WARNING: The contents of this file is automatically generated by the
 * genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the tcllibxml2.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

Tcllibxml2Stubs tcllibxml2Stubs = {
    TCL_STUB_MAGIC,
    NULL,
    Tclxml_libxml2_Init, /* 0 */
    NULL, /* 1 */
    TclXML_libxml2_InitDocObj, /* 2 */
    TclXML_libxml2_NewDocObj, /* 3 */
    TclXML_libxml2_CreateObjFromDoc, /* 4 */
    TclXML_libxml2_GetDocFromObj, /* 5 */
    TclXML_libxml2_GetTclDocFromObj, /* 6 */
    TclXML_libxml2_GetTclDocFromNode, /* 7 */
    TclXML_libxml2_DestroyDocument, /* 8 */
    TclXML_libxml2_DocKeep, /* 9 */
    TclXML_libxml2_ErrorHandler, /* 10 */
    TclXML_libxml2_ResetError, /* 11 */
    TclXML_libxml2_GetErrorObj, /* 12 */
    TclXML_libxml2_SetErrorNodeFunc, /* 13 */
};

/* !END!: Do not edit above this line. */
