/* 
 * tcldomxmlStubInit.c --
 */

#include <tcldom-libxml2/tcldomlibxml2.h>

/*
 * Remove macros that will interfere with the definitions below.
 */


/*
 * WARNING: The contents of this file is automatically generated by the
 * genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the tcldomxml.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

Tcldom_libxml2Stubs tcldom_libxml2Stubs = {
    TCL_STUB_MAGIC,
    NULL,
    Tcldom_libxml2_Init, /* 0 */
    NULL, /* 1 */
    NULL, /* 2 */
    NULL, /* 3 */
    NULL, /* 4 */
    NULL, /* 5 */
    NULL, /* 6 */
    TclDOM_libxml2_CreateObjFromNode, /* 7 */
    TclDOM_libxml2_GetNodeFromObj, /* 8 */
    TclDOM_libxml2_GetTclNodeFromObj, /* 9 */
    TclDOM_libxml2_NewEventObj, /* 10 */
    TclDOM_libxml2_GetEventFromObj, /* 11 */
    TclDOM_libxml2_GetTclEventFromObj, /* 12 */
    TclDOM_libxml2_DestroyNode, /* 13 */
    TclDOM_libxml2_InvalidateNode, /* 14 */
    TclDOM_libxml2_CreateObjFromDoc, /* 15 */
    NULL, /* 16 */
    NULL, /* 17 */
    NULL, /* 18 */
    NULL, /* 19 */
    TclDOM_InitEvent, /* 20 */
    TclDOM_InitUIEvent, /* 21 */
    TclDOM_InitMouseEvent, /* 22 */
    TclDOM_InitMutationEvent, /* 23 */
    TclDOM_PostUIEvent, /* 24 */
    TclDOM_PostMouseEvent, /* 25 */
    TclDOM_PostMutationEvent, /* 26 */
    TclDOM_AddEventListener, /* 27 */
    TclDOM_RemoveEventListener, /* 28 */
    TclDOM_DispatchEvent, /* 29 */
    TclDOM_GetEventListener, /* 30 */
};

/* !END!: Do not edit above this line. */
